namespace: "Chile"
language: "es"

properties:
  - 
    label: "localidad de"
    description: "entidad de población urbana grande"
    datatype: "wikibase-item"
    aliases: ["localidad", "área urbana"]


items:
  - 
    label: "Territorio"
    description: "una región del mundo"
    aliases: ["región", "área"]

  - 
    label: "País"
    description: "entidad territorial o política distinta"
    aliases: ["países"]
    statements:
      -
        label: "subclase de"
        value: "Territorio"
        datatype: "wikibase-item"

  - 
    label: "Chile"
    description: "País en América del Sur"
    aliases: ["país chileno"]
    statements:
      -
        label: "instancia de"
        value: "País"
        datatype: "wikibase-item"
        qualifiers:
          -
            label: "etiqueta"
            value: "Chile"
            datatype: "string"

          -
            label: "descripción"
            value: "País en América del Sur"
            datatype: "string"
        references:
          -
            label: "dirección web de la referencia"
            value: "https://www.britannica.com/place/Chile"
            datatype: "url"

  - 
    label: "ciudad"
    description: "entidad de población urbana grande"
    aliases: ["ciudades", "área urbana"]
    statements:
      -
        label: "subclase de"
        value: "Territorio"
        datatype: "wikibase-item"
  
  -
    label: "Santiago"
    description: "ciudad de Chile"
    aliases: ["capital de Chile"]
    statements:
      -
        label: "instancia de"
        value: "ciudad"
        datatype: "wikibase-item"
        references:
          -
            label: "dirección web de la referencia"
            value: "https://www.munistgo.cl/"
            datatype: "url"
      - 
        label: "localidad de"
        value: "Chile"
        datatype: "wikibase-item"